### ISSUE TITLE
Why explicit disconnect() is needed?

### ISSUE THREAD

**Issue by raub** [LabSound/LabSound#88] opened 2018-05-19 09:09 UTC
Hi! I've been having a problem with **segfault**, while trying to delete an instance of `SampledAudioNode`. Actually it got deleted by the `shared_ptr`, but that's not too important. I've managed to reproduce the behavior in a short example [here](https://github.com/raub/LabSound/blob/15976b26e4dcdc9fa9dc6ba9e7c0e2e0c43ad211/examples/src/UsecaseDisconnect.h#L59).

So the question is why should I care about calling the `disconnect()` when the node is to be deleted? It probably becomes even worse with smart pointers, since I don't know when specifically it is deleted.

**Comment by ddiakopoulos** [comment] 2018-05-22 23:51
This is a complex issue. The lifetime of most regular AudioNode objects are not managed by the AudioContext except in limited cases (the listener, the destination node). Nodes create their own AudioBus inputs/outputs and those pointers get set on nodes potentially upstream or downstream in the graph. Disconnect makes this cleanup explicit. 

I remember talking to @meshula about this issue in the past, and we might have a potential solution where the node would lock the graph in its destructor, but this needs to be prototyped and tested.

**Comment by raub** [comment] 2018-05-23 06:15
What I do now is to simply [call](https://github.com/node-3d/webaudio-raub/blob/master/cpp/audio-node.cpp#L108) the `disconnect()` in my **wrapper**'s destructor. That seems legit to me. The only reason not to carry it into the `AudioNode`'s destructor is that it doesn't know who's the context, whilst in my wrapper I don't have this limitation.

**Comment by meshula** [comment] 2018-05-23 16:01
If this is the same issue I previously investigated, the problem is that input and output pointers on other nodes point to deleted memory for one rendering callback where the crash occurs. Your workaround of calling disconnect ensures this fault does not occur. We have discussed possible fixes, but have not thought of one that does not have a performance or complexity penalty.

**Comment by meshula** [comment] 2020-01-08 07:14
I believe that this issue no longer occurs on the master branch due to reworking of the shutdown logic. The mac_on_rtaudio branch definitely solves this one by not passing pointers to external memory into the processing graph. I'm going to close this one now; @raub, please let us know if this issue still occurs.

**Closed by meshula** 2020-01-08 07:14 UTC
Labels: enhancement, question
