### ISSUE TITLE
[data race] - can not safe update impulse.

### ISSUE THREAD

**Issue by imiskolee** [LabSound/LabSound#167] opened 2021-06-26 11:53 UTC
program ma crash att

```
#0	0x00000001013d847c in lab::sp_conv_compute(lab::sp_data*, lab::sp_conv*, float*, float*) ()
```

when dynamic update impulse. I think it's data race issue. so can we have a solution for safely update value, locker is ok.

**Comment by meshula** [comment] 2021-07-02 02:23
Is this report a duplicate of #166, or is it for a different node?

**Comment by meshula** [comment] 2021-09-18 23:03
Added a mutex for thread safety. https://github.com/LabSound/LabSound/commit/9daad90c71f6a59c93d0afe7cb198651e9b4c797 Please reopen if the crash happens again!

**Closed by meshula** 2021-09-18 23:03 UTC
Labels: information needed
